language: scala
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://github.com/CommBank/ci.git
- chmod ugo+x ci/*
- ci/sbt-setup.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package'
- ci/sbt-deploy.sh
after_script:
- rm -rf ci
env:
  global:
    secure: oBByGcMkZ75E4vv0emC3Sj8cRuw5PPSPd2DsU9QtKset8WJQqkC9WpAIdP6lb3hfuxbgy++NtmdACAN0FumaydOO8LyN6gc97ibCRf2FK00oKZ9Fm8aqpSsdWYUroeCq9+sGz3TCZNkObFk+Mf6+vQd33lUNJsBwBt7PdYdvioQ=
